spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:lbs}"
    username: "${DB_USER:lbs}"
    password: "${DB_PASSWORD:lsb123}"
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        temp:
          use_jdbc_metadata_defaults: "false"
    database-platform: "org.hibernate.dialect.PostgreSQL9Dialect"
    generate-ddl: "false"
  liquibase:
    change-log: classpath:db/liquibase-changelog.yml
  main:
    allow-circular-references: true

banner:
  location: "classpath:/banner.txt"

logging:
  file: ${LBS_LOG:/lbs/log/app.log}
  level:
    com.lbs: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %logger{25} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %logger{25} - %msg%n"

security.secret: ${SECURITY_SECRET:random_secret_hfjdsk72euhdsbcgg6}
telegram.token: ${TELEGRAM_TOKEN}

